version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  apache:
    image: php:8.2-apache  # Você pode trocar para outra versão do PHP, como 8.1-apache
    container_name: php-apache-container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html  # Pasta onde estão seus arquivos PHP


volumes:
  db_data:
